// Copyright (c) 2025 Open Technologies for Integration
// Licensed under the MIT license (see LICENSE for details)

import '../global.scss'

export const metadata = {
  title: "App Connect Deployment planner",
  description: "Generated by App Connect Enterprise",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}




